### ISSUE TITLE
setConfig error in 0.107.7

### ISSUE THREAD

**Issue by pollinolas** [bramkragten/swipe-card#11]
I have this issue in v3.0.0 ,after reload page several times it load correctly,if I update to v3.1.0 ,all cards inside swipe-card are black and cant see nothing only  the scrollbard.
```
t.setConfig is not a function
type: 'custom:swipe-card'
start_card: 1
parameters:
  nested: true
  centeredSlides: true
  slidesPerView: 1
  spaceBetween: 8
  scrollbar:
    hide: false
    draggable: true
    snapOnRelease: true
cards:
  - type: vertical-stack
    cards:
      - type: picture-elements
        image: /local/images/casa.jpg
        elements:
          - type: 'custom:decluttering-card'
            template: garaje
            variables:
              - name: Puerta Garaje
              - entity: switch.puerta_garaje
              - entity_2: binary_sensor.sensor_puerta_garaje
            style:
              top: 20%
              left: 15%
```
