### ISSUE TITLE
Swiper is not shown when using a narrow browser window

### ISSUE THREAD

**Issue by carlba** [bramkragten/swipe-card#16]
When I start the HA UI in a narrow browser window I get this error:

![image](https://user-images.githubusercontent.com/1884191/80908891-f0b53280-8d23-11ea-91e6-5b4c205f6cf4.png)

For this configuation:

```yaml
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.235_temperature
                name: Temp - Outside
                height: 60
                width: 30
                line_color: "#3498db"
              - type: sensor
                entity: sensor.air_purifier_temperature
                name: Temp - Inside
                height: 60
                width: 30
                line_color: "#3498db"
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.air_purifier_humidity
                name: Humidity - Inside
                height: 60
                width: 30
                line_color: "#3498db"
              - type: sensor
                entity: sensor.xiaomi_air_quality_monitor
                name: Air Quality - Inside
                height: 60
                width: 30
              - type: sensor
                entity: sensor.s10_batterylevel
                name: Samsung S10 Battery Level
                height: 60
                width: 30
          - type: entity-filter
            entities:
              - person.carl
              - person.johanna
            state_filter:
              - 'home'
            card:
              type: glance
              show_state: false
              show_name: false
              title: '@home'
          - type: glance
            entities:
              - timer.toaster
              - timer.coffeemaker
              - timer.clean
```
