### ISSUE TITLE
Link to "page" within swiper

### ISSUE THREAD

**Issue by raffertyp1** [bramkragten/swipe-card#2]
Is it possible to add a url/location hash on each card within the swiper, so that you can navigate to predefined location in the swiper container?

I have a set of entity buttons that display the temperatures in my house. Below that, I have a swiper container with the graphs of the temperature history for each of those room's. I'd like to use the navigate action within the button to display the associated temperature graph in the swiper.

**Comment by matt8707** [comment]
I just tried this out as I would like to automate between swipe cards. It doesn't work...

 I added `<div class="swiper-slide" data-hash="slide1">Slide 1</div>` to swipe-card.js

```html        
<div class="swiper-wrapper">
${this._cards}
<div class="swiper-slide" data-hash="slide1">Slide 1</div>
</div>
```
Then added the hashNavigation parameter

```yaml
- cards:
...
parameters:
  hashNavigation:
    watchState: true
type: 'custom:swipe-card'
```
And it works if you type in #slide1 in the adress bar. But it **doesn't** work using the navigate action...

```yaml
tap_action: 
  action: navigate
  navigation_path: '#slide1'
```

The url changes but not the swipe card because the navigate action is not a "html link"...
