### ISSUE TITLE
Sync two swipers like in “Thumbs Gallery” example

### ISSUE THREAD

**Issue by schmurtzm** [bramkragten/swipe-card#25]
Awesome card, thank you. 
Can we make a “Thumbs Gallery” with it ?
[The example of “Thumbs Gallery” from the swiper website.](https://stackblitz.com/edit/swiper-demo-30-thumbs-gallery?file=index.html)

I tried to make a simple example and I’m not sure that what I’m trying to do is possible…
In fact the “Thumbs” component is a way to sync two swipers so the main swiper has another instance of a swiper in parameter 🧐 :

 ```yaml
type: vertical-stack
cards:
  - type: 'custom:swipe-card'
    title: MainSwiper
    parameters:
      navigation: null
      keyboard:
        enabled: true
        onlyInViewport: true
      Thumbs:
        swiper: SubSwiper
        autoScrollOffset: 1
    cards:
      - type: sensor
        entity: sensor.temp_0
      - type: sensor
        entity: sensor.temp_1
      - type: sensor
        entity: sensor.temp_2
      - type: sensor
        entity: sensor.temp_3
  - type: 'custom:swipe-card'
    title: SubSwiper
    card_width: 185px
    parameters:
      freeMode: true
      grabCursor: true
      spaceBetween: 10
      watchSlidesVisibility: true
      watchSlidesProgress: true
      slidesPerView: 2
    cards:
      - type: sensor
        entity: sensor.temp_0
      - type: sensor
        entity: sensor.temp_1
      - type: sensor
        entity: sensor.temp_2
      - type: sensor
        entity: sensor.temp_3

```

So three question about the code example below (which doesn’t work) :

1. Is vertical stack the right way to do it?
2. Can I instantiate my sub swiper in the main swiper ?
3. So can I achieve that ? 😋 

Thank you.
