### ISSUE TITLE
Swipe Card Template

### ISSUE THREAD

**Issue by jazzyisj** [bramkragten/swipe-card#27]
Having a template ([like the custom button card](https://github.com/custom-cards/button-card)) would be great.  

I use several swipe cards throughout my lovelace, most with the same parameters.  Would be nice to be able to template those to save on duplication and having to track them all down to make changes.

Love the card!  Thank you!

**Comment by jazzyisj** [comment]
Forgot all about this.  Mostly resolved by using an include directive for parameters.

`parameters: !include /config/lovelace/lovelace_swipe_parameters_auto_height.yaml`

the contents of which are...

```
autoHeight: true
centeredSlides: true
effect: coverflow
coverflowEffect:
  depth: 100
  modifier: 1
  rotate: 0
  scale: 1
  slideShadows: true
  stretch: 0
pagination:
  type: bullets
spaceBetween: 20
speed: 500
```
