### ISSUE TITLE
Hold action not executed

### ISSUE THREAD

**Issue by Mariusthvdb** [bramkragten/swipe-card#35]
using:
```
type: custom:button-card
template: button_body
entity: binary_sensor.ha_update_available
icon: mdi:home-assistant
name: Core update
show_state: false
tap_action:
  action: more-info
  entity: sensor.ha_available_version
hold_action:
  action: url
  url_path: https://github.com/home-assistant/core/releases
```

on a button-card works perfectly. However when this card is displayed in the swiper, it (almost) always show the more-info, if anything. Funny thing is, when I go to a view where this same card is always shown, the more-info works fine, and then going back to the swiper, makes it work....

Its not a matter of clicking on the right spot, the handle turns in to the correct pointing hand (and the more-info circle doesnt show either)

**Comment by ASNNetworks** [comment]
I experienced this same issue a few months ago when I started to use swiper card. I have found a way to invoke hold action by accident on browsers. This works 100 of the time and I’ve been doing it this way for months now.

Press and hold right click on an icon till you see the hold_action effect (the little circle effect). Then let go and single press left click. All buttons inside that swiper card will open hold_action now with left click. To stop, just single press right click and then left click works as toggle again.

If you have a slider inside a swiper card, then it’s a little more complicated. Then you need to hold right click first and then hold left click (without letting right click off) and drag with both fingers. This means you need a mouse with both buttons (so Apple magic mouse is not usable for instance). But perhaps you can also use macro’s of function key for that.

Other users noticed this as well and one reported this:

```
I found an interesting thing. From chrome in dev tools, with the toggle device toolbar, we can use properly hold and click actions
Question : Is it possible to force applicationize.me 2 to work in with the “toggle device toolbar” and emulate a tablet ? (User agent ?)
```

Mattias noticed this with glace card as well. So I think it applies to all cards inside swiper-card: https://github.com/bramkragten/swipe-card/issues/7

**Comment by Mariusthvdb** [comment]
to add: the 'funny' experience from my opening post can now be explained some more:

right hold clicking the button in the slider apparently toggle the action (if it was hold, it changes to tap and vv). So I can right click hold, see the hold circle show (still in the slider) and next tap, to perform the original hold. It navigate to the other view. repeating that sequence sets it back to tap action, etc etc. How odd.

**Comment by ASNNetworks** [comment]
Yes, you can also right click anywhere on an empty space, which will revert it back to normal and left click will then register as tap_action again.

**Comment by Mariusthvdb** [comment]
by accident I discovered today using https://community.home-assistant.io/t/lovelace-ui-minimalist/322687/27?u=mariusthvdb that the hold_actions are executed on iPhone.

```
  - type: custom:swipe-card
    parameters:
      spaceBetween: 8
      freeMode: true
    cards:
      - !include /config/lovelace/includes/include_chip_temperature.yaml
      - !include /config/lovelace/includes/include_chip_presence.yaml
      - !include /config/lovelace/includes/include_chip_energy.yaml
```
now which issue should this be then, a general frontend issue, or still Swiper card issue?
