### ISSUE TITLE
Request: Is possible to add auto slide and time for auto slide?

### ISSUE THREAD

**Issue by mohyat** [bramkragten/swipe-card#37]
Hi,

Is possible to add auto slide and time for auto slide option?

thx

**Comment by adapdoaosdaoda** [comment]
add
```
type: custom:swipe-card
parameters:
  autoplay:
    delay: 5000
```
delay is in ms

more autoplay parameters can be found here: https://swiperjs.com/swiper-api#autoplay
