### ISSUE TITLE
Error t.setConfig is not a function

### ISSUE THREAD

**Issue by Rendeik** [bramkragten/swipe-card#38]
I updated from 2021.7 to 2021.8.3 and now it gives me this error.
t.setConfig is not a function

**Comment by saxopwn** [comment]
Also getting this issue. Loads sometimes on my PC but never on the iOS app/Safari browser:

```
type: custom:swipe-card
cards:
  - type: picture-glance
    title: Front
    entities: []
    camera_image: camera.front
    camera_view: live
  - type: picture-glance
    title: Doorbell
    entities: []
    camera_image: camera.doorbell
    camera_view: live
    aspect_ratio: '16:9'
  - type: picture-glance
    title: Garage
    entities: []
    camera_image: camera.garage
    camera_view: live
  - type: picture-glance
    title: Backyard
    entities: []
    camera_image: camera.backyard
    camera_view: live
  - type: picture-glance
    title: Entryway
    entities: []
    camera_image: camera.entryway
    camera_view: live
  - type: picture-glance
    title: Kitchen
    entities: []
    camera_image: camera.kitchen
    camera_view: live
```
