### ISSUE TITLE
Unable to access input field of custom:notify-card

### ISSUE THREAD

**Issue by F1DNA** [bramkragten/swipe-card#45]
Tested the notify card on it's own, works fine.  Once inside of swipe-card, I can swipe between cards fine.  None of them allow me to access the input field.

```
type: custom:swipe-card
cards:
  - type: custom:notify-card
    card_title: Message Center (Swipe for more)
    target: tablet
    label: Message the house
  - type: custom:notify-card
    card_title: Message Center (Swipe for more)
    target:
      - target: mobile_app_steve_s_phone
      - target: mobile_app_heather_s_phone
    label: Message both phones
    notification_title: Message from kitchen tablet
  - type: custom:notify-card
    card_title: Message Center (Swipe for more)
    target: mobile_app_steve_s_phone
    label: Message Steve's phone
    notification_title: Message from kitchen tablet
  - type: custom:notify-card
    target: mobile_app_heather_s_phone
    label: Message Heather's phone
    card_title: Message Center (Swipe for more)
    notification_title: Message from kitchen tablet
```
