### ISSUE TITLE
Add a box-shadow to the card

### ISSUE THREAD

**Issue by ildar170975** [bramkragten/swipe-card#51]
Currently the card:
- does not allow to show box-shadows for child cards;
- does not have it's own box-shadow.

```
type: custom:swipe-card
cards:
  - type: button
    entity: sun.sun
  - type: button
    entity: zone.home
```

![image](https://user-images.githubusercontent.com/71872483/170968166-81d83992-b593-4331-ae6c-c8ba7640f3c8.png)

**Comment by ildar170975** [comment]
> 3d option (which I use) is have the cards all have their own style/box-shadow setting

No, it does not help.
Initially inserted cards may already have their own box-shadow properties.
Their shadows just cannot be seen since they are overlapped by swipe-card.
To be sure - check this example:
```
type: custom:swipe-card
cards:
  - type: entities
    entities:
      - sun.sun
    card_mod: &ref_0
      style: |
        ha-card {
          box-shadow: var( --ha-card-box-shadow,0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) );
          color: red;
        }
  - type: entities
    entities:
      - zone.home
    card_mod: *ref_0
```
As you can see the inserted cards have a shadow property:
![image](https://user-images.githubusercontent.com/71872483/171048544-8da23708-142b-49e2-90c4-5aa63a83bf3b.png)
but it is not visible:
![image](https://user-images.githubusercontent.com/71872483/171048476-21c71604-590e-4084-9bb4-91e698e2dbed.png)

**Comment by Mariusthvdb** [comment]
must check that, because I hadnt noticed in my setup:

<img width="518" alt="Schermafbeelding 2022-05-30 om 21 07 45" src="https://user-images.githubusercontent.com/33354141/171048865-27b6c7bb-23fa-446d-8557-d4d328c887d8.png">


ofc, I have a minimal box-shadow (must correct myself above, it is not defined in the button_card_templates, but in my theme settings):
```
    ha-card-border-radius: 0px
    ha-card-box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)
```

**Comment by ildar170975** [comment]
All checks I usually do with a default theme to be sure that my themes do not affect the output.
Cannot say anything about your example since you are using a custom theme.

**Comment by ildar170975** [comment]
> btw, never checked myself, but did you try: https://swiperjs.com/swiper-api#param-cardsEffect-slideShadows ?

Here are my tests:

1. Effect=cards:
No shadows visible.
![image](https://user-images.githubusercontent.com/71872483/171055050-c9589350-4a14-4ccf-a711-95353dc49322.png)

2. Effect=flip:
Shadows=OK.
![image](https://user-images.githubusercontent.com/71872483/171055163-617cb40b-dd73-44e6-bd4d-27d583a5ae2f.png)

3. Effect=coverflow:
Shadows are visible only during swiping.
![image](https://user-images.githubusercontent.com/71872483/171055222-789fb4ab-59a4-41b2-91c7-6c31d5f7d37a.png)


As for "creative" - did not manage to specify a [creatriveEffect](https://swiperjs.com/swiper-api#param-creativeEffect) object.
In my test it seems to work like a "cards" case:
![image](https://user-images.githubusercontent.com/71872483/171055496-072cdf5c-4c1b-4d01-8095-875bc30f9e8c.png)

**Comment by ildar170975** [comment]
Finally:
1. This is not a "no box-shadow" problem. This is a "swip-card is clipping other' cards' borders".
2. If `swipe-card` does not contain any stacks - use one of these solutions:
- place the `swipe-card` inside `stack-in-card` (https://github.com/bramkragten/swipe-card/issues/51#issue-1252505591);
- use card-mod (https://github.com/bramkragten/swipe-card/issues/51#issue-1252505591);
- use `slideShadows: true` (works only with `effect: flip`) (https://github.com/bramkragten/swipe-card/issues/51#issuecomment-1141457614)

3. If `swipe-card` contains a stack - then there is no universal solution, it is to be found dependingly on a particular case)))

**Comment by estevez-dev** [comment]
If you have multiple `slidesPerView` cards, you can add additional margin for each inner card inside `swipe-card` with `card-mod`:

```
    card_mod:
      style: |
        ha-card {
          margin: 3px;
        }
```

**Comment by damru** [comment]
To avoid the shadow being hidden with `coverflow` effect, you can use the new [dictionary syntax of card mod](https://github.com/thomasloven/lovelace-card-mod#dom-navigation) to handle shadow DOM:

```
type: custom:mod-card
card:
  type: custom:swipe-card
  parameters:
    effect: coverflow
  cards:
    - type: button
      entity: sun.sun
    - type: button
      entity: zone.home
style:
  swipe-card$: |
    .swiper-container {
      margin: -2px !important;
      padding: 2px !important;
    }

```

**Comment by cloudbr34k84** [comment]
Hey all, how would i go about fixing the box shadow on my mushroom cards which make up 1 big card
```
type: custom:swipe-card
start_card: 1
parameters:
  autoHeight: false
  initialSlide: 0
  centeredSlides: true
  effect: coverflow
  loop: false
  preventClicksPropagation: true
  preventClicks: true
cards:
  - type: vertical-stack
    cards:
      - type: custom:mushroom-title-card
        title: null
        subtitle: Favourite Sensors
      - square: false
        columns: 3
        type: grid
        cards:
          - type: custom:mushroom-template-card
            primary: Climate
            secondary: >-
              {{ states('sensor.downstairs_average_humidity')}} % / {{
              states('sensor.downstairs_average_temperature')}} °C
            icon: mdi:water-thermometer
            icon_color: '#A6ACAF'
            tap_action:
              action: none
          - type: custom:mushroom-template-card
            secondary: '{{ states(''sensor.fronius_live_power_flow_kwh'')}} kWh'
            primary: Power Flow
            icon: '{{ state_attr(''sensor.fronius_live_power_flow_kwh'', ''icon'') }}'
            entity: sensor.fronius_live_power_flow_kwh
            icon_color: '#A6ACAF'
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
            fill_container: false
            multiline_secondary: true
            badge_color: ''
            card_mod:
              style:
                mushroom-shape-icon$: |
                  .shape {
                    box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.16) !important;}
```
![image](https://user-images.githubusercontent.com/58960644/202929501-de120fe2-4821-457a-8002-249f0ce94075.png)

**Comment by ingeniumdesign** [comment]
same problems

**Comment by antonio1475** [comment]
> 
> 1. Insert the card into `custom:stack-in-card`:
> 
> ```
> type: custom:stack-in-card
> cards:
>   - type: custom:swipe-card
>     cards:
>       - type: button
>         entity: sun.sun
>       - type: button
>         entity: zone.home
> ```
> 
> **which is not a perfect solution since the `stack-in-card` does not seem to be maintained.**

Using the "successor" [custom:vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card) works perfectly. Thank you for the workaround

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:swipe-card
    cards:
    - type: 'custom:button-card' 
      template:
        - custom_card_room_8
        - yellow_on
      name: Entrada
      entity: light.entrada
      icon: mdi:door-closed

    - type: picture-glance
      camera_view: live
      entities: []
      camera_image: camera.entrada_hd
      aspect_ratio: '1'
      card_mod:
        style: |
          div.box {display:none; }
```

Only the bottom one (Entrada) is in a custom:vertical-stack-in-card
![image](https://user-images.githubusercontent.com/63130724/230719679-f3a120a0-1b0e-43fc-8d13-0c770e3457b7.png)


Without (issue):
![image](https://user-images.githubusercontent.com/63130724/230719752-ea2649ec-3797-4dff-a83d-433f522f6f3a.png)
