### ISSUE TITLE
Swipe-card inside config-template-card glitches

### ISSUE THREAD

**Issue by ildar170975** [bramkragten/swipe-card#56]
If `swipe-card` is placed inside a `config-template-card` some glitches are observed:
```
type: custom:config-template-card
entities:
  - sun.sun
card:
  type: custom:swipe-card
  start_card: 3
  cards:
    - type: entities
      entities:
        - sun.sun
    - type: entities
      entities:
        - sun.sun
        - sun.sun
    - type: entities
      entities:
        - sun.sun
        - sun.sun
        - sun.sun
    - type: entities
      entities:
        - sun.sun
        - sun.sun
        - sun.sun
        - sun.sun
```

A glitch is displayed on the right side:
![image](https://user-images.githubusercontent.com/71872483/190937576-feb75cb0-97e4-4128-a2cc-819f69c7c74f.png)

Also `start_card` option is ignored - the card No.3 is not set as an initial.
