### ISSUE TITLE
Adding the ability to define hash values for each card within swipe-card

### ISSUE THREAD

**Issue by TinyShark** [bramkragten/swipe-card#68]
The Swiper API has hash navigation built in and it can be enabled with the following config parameters on swipe-card:
```
type: custom:swipe-card
parameters:
  slidesPerView: auto
  hashNavigation:
    watchState: true
```

This works as it should if I manually add `data-hash="[my-hash-value]"` to the class of the desired slide through chrome dev tools:

<img width="649" alt="Screenshot 2023-01-24 at 10 45 36" src="https://user-images.githubusercontent.com/23080224/214272199-6f61009c-fbce-4faa-8c73-877aac46ffb0.png">

and then use javascript to set the hash: `window.location.hash = 'testhash';` Swipe card transitions to that specific slide.

Would it be possible to add an option/field to define a hash value per card?

for eg:

```
type: custom:swipe-card
parameters:
  slidesPerView: auto
  hashNavigation:
    watchState: true
cards:
  - type: vertical-stack
    hash: my-hash-value
```

thanks!
