### ISSUE TITLE
Please add support for "picture-glance" type (sec.cam.video)

### ISSUE THREAD

**Issue by banditto9** [bramkragten/swipe-card#71]
Hello and many thanks for the wonderful swipe-card. I like it a lot and it suits well for a wall-panel setups.
Unfortunately, it seems that a standard HA "picture-glance" type is not supported - it says "invalid configuration", other cards like entity ones are ok. Can you please consider a possibility to add support for a card of this type?
It would be great to have a swipe-enabled picture preview cards from CCTV cameras on the wall panels.
Thank you for your time and support!

**Comment by antonio1475** [comment]
I'm using picture glance and it works okay

```
type: custom:swipe-card
cards:
  - type: 'custom:button-card' 
    template:
      - custom_card_room_8
      - yellow_on
    name: Entrada
    entity: light.entrada
    icon: mdi:door-closed

  - type: picture-glance
    camera_view: live
    entities: []
    camera_image: camera.entrada_hd
    aspect_ratio: '1'
    card_mod:
      style: |
        div.box {display:none; }
```
