### ISSUE TITLE
swiper card in tabbed card > preview OK, result extremely large

### ISSUE THREAD

**Issue by TAGVL** [bramkragten/swipe-card#75]
I tried adding a swiper card to my dashboard with below code. The preview looks promessing but once I save it the swiper card gets gigantic and shows 99,9% blank. When I swipe to Neerslag-card I get no preview in the saved dashboard. Code I use is below. Note; I use this piece of code in a tabbed card (code also below). Any idea what I'm doing wrong / what is missing? If I use the swiper card directly on the dashboard, so not in a tabbed card, it seems to work propperly.

![swipe preview](https://user-images.githubusercontent.com/78881168/234263377-a745a80b-3c25-4a56-893d-465e28a79d2f.jpg)

Code of swiper card

```
type: custom:swipe-card
cards:
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.xxxx
  - type: custom:neerslag-card
    entity: sensor.neerslag_buienalarm_regen_data
    title: Neerslag
```

Code of complete tabbed card:
```
type: vertical-stack
cards:
  - type: custom:swipe-card
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.xxxx
  - type: custom:neerslag-card
    entity: sensor.neerslag_buienalarm_regen_data
    title: Neerslag
  - type: custom:mushroom-media-player-card
    entity: media_player.woonkamer
    icon: mdi:volume-high
    fill_container: false
    name: HomePod
    volume_controls:
      - volume_mute
      - volume_set
      - volume_buttons
    media_controls:
      - on_off
      - shuffle
      - previous
      - play_pause_stop
      - next
      - repeat
    collapsible_controls: true
view_layout:
  grid-area: middle
```
