### ISSUE TITLE
Interacting with a slider inside a swipe card, also swipes the card.

### ISSUE THREAD

**Issue by Pabsilon** [bramkragten/swipe-card#78]
Hello,

When using cards with a slider inside the swipe cards, clicking and moving the slider also swipes the card, which I think in general is undesirable.

In my case, I have a grid card with various swipe cards that contain Tile cards with the brightness feature. Here's how that would end up in yaml:

```
square: false
type: grid
columns: 1
cards:
  - type: custom:swipe-card
    cards:
      - type: tile
        entity: light.light1
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        features:
          - type: light-brightness
      - type: tile
        entity: light.light2
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
        features:
          - type: light-brightness
```

The light has to be dimmable for this to work properly, but you get the idea.

![image](https://github.com/bramkragten/swipe-card/assets/9048617/72e6a350-b55f-481a-aef8-4c97fea57413)

![image](https://github.com/bramkragten/swipe-card/assets/9048617/50ecf449-4da9-43bf-aff8-3ea1a0c44749)
