### ISSUE TITLE
setConfig error after upgrade to 0.107.1

### ISSUE THREAD

**Issue by jeremywillans** [bramkragten/swipe-card#9]
Following upgrade to 0.107.1 I get the following issue when using the swipe-card

![image](https://user-images.githubusercontent.com/31495062/77138954-c7b44780-6abf-11ea-88e6-281f3d5d849d.png)

Test Config
```
cards:
  - card:
      content: |
        Test Markdown Card
      type: markdown
    conditions:
      - entity: input_boolean.vacation
        state: 'on'
    type: conditional
parameters:
  allowTouchMove: true
  autoplay:
    disableOnInteraction: false
  effect: coverflow
  grabCursor: true
type: 'custom:swipe-card'
```
