### ISSUE TITLE
Bug: Swipe card with nested button-cards on iOS

### ISSUE THREAD

**Issue by Lorenzo-N** [bramkragten/swipe-card#93]
Hi, if I have a swipe-card containing a button-card with sub-elements inside (as in many templates of Lovelace Minimalist UI), swipe doesn't work on iOS, both in Safari and the app.
Example configuration:
```
type: custom:swipe-card
cards:
  - type: custom:button-card
    name: Outer element
    styles:
      grid:
        - grid-template-areas: '"item1" "n"'
    custom_fields:
      item1:
        card:
          type: custom:button-card
          name: Nested element
```
![image](https://github.com/user-attachments/assets/ba9b11dd-7929-4a4c-9070-01c5e3b3c96b)

In the example, if the swipe starts from the outer element, it works correctly. However, if it starts from the nested element, it doesn't move, as if the nested element stops the propagation of touch events. On Windows, it works fine even when simulating a mobile device via Inspect Element.

The only solutions I've found are:

- Adding **pointer-events: none** to the nested element, but this prevents all click events as well.
```
   card_mod:
      style: |
        #item1 {
          pointer-events: none;
        }
```
- Enabling the **cssMode of Swiper**, but with this, only the basic slide effect works.

Has anyone encountered the same issue? How can I solve it?
